---
- name: Check docker gpg key.
  shell: apt-key list | grep 2C52609D
  register: docker_gpg
  ignore_errors: True
  changed_when: False

- name: Add docker gpg key.
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  when: docker_gpg | failed

- name: Copy docker.list file.
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644

- name: Upgrade packages.
  apt: upgrade=yes update_cache=yes

- name: Install zsh
  apt: name=zsh
